block_definitions:
    ezcontent_field:
        name: 'eZ content field'
        icon: '/bundles/netgenlayoutsezplatform/images/blocks/icon-ezcontent_field.svg'
        view_types:
            ezcontent_field:
                name: 'eZ content field'

    ezcomponent:
        name: 'eZ component'
        icon: '/bundles/netgenlayoutsezplatform/images/components/icon-component-generic.svg'
        enabled: false
        config_provider: ezplatform
        view_types:
            standard:
                name: 'Standard'
