parameters:
    netgen_layouts.app.ibexa.item_preview_template: '@@nglayouts_admin/app/item/nglayouts_app_preview.html.twig'
    netgen_layouts.ibexa.admin.pagelayout: '@@NetgenLayoutsIbexa/admin/pagelayout.html.twig'
